pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
    resolutionStrategy {
        eachPlugin {
            if (requested.id.namespace == 'io.github.damian1000') {
                useModule("com.github.damian1000.build-conventions:plugins:${requested.version}")
            }
        }
    }
}

rootProject.name = 'sudoku-dancing-links'
